# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

source 'https://github.com/arif-arrijal/dicoding-core-podspecs'

use_frameworks!
 
workspace 'Modularization'

target 'katalog1' do
  pod 'Alamofire', '~> 5.2'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SDWebImage'
  pod 'SwiftLint'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'Core'
end

target 'Common' do
  project '../Common/Common'
end

target 'Game' do
  project '../Game/Game'
  pod 'RxSwift', '6.2.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Core'
end

target 'User' do
  project '../User/User'
  pod 'RxSwift', '6.2.0'
  pod 'Core'
end
